// =============================================================================
// workflow/loader.rs — Read and deserialize a workflow YAML file
//
// This module does exactly one thing: given a file path, it:
//   1. Reads the raw text from disk          (may fail: file not found, permission)
//   2. Parses the YAML into our Workflow type (may fail: invalid YAML, missing fields)
//   3. Runs semantic validation               (may fail: bad step references, etc.)
//   4. Returns the fully-populated Workflow   (or a descriptive WorkflowError)
//
// Keeping this logic in its own file makes it easy to swap the file-reading
// step for, say, a `from_str` variant used in tests.
// =============================================================================

use std::fs;         // standard-library file-system utilities
use std::path::Path; // borrowed path type (like &str, but for paths)

use crate::error::WorkflowError;

// `super::` refers to the parent module — workflow/mod.rs.
// We use the re-exported `Workflow` and the private `validate_workflow`.
use super::{Workflow, validate::validate_workflow};

/// Load, parse, and validate a workflow from a YAML file.
///
/// Returns a fully-populated `Workflow` on success, or a `WorkflowError`
/// describing the first class of problem encountered (IO, YAML, validation).
pub fn load_workflow(path: &Path) -> Result<Workflow, WorkflowError> {
    // Step 1: read the file contents into a String.
    // `map_err` converts the generic `std::io::Error` into our specific
    // `WorkflowError::ReadFile` variant, which also captures the path.
    let raw = fs::read_to_string(path).map_err(|source| WorkflowError::ReadFile {
        path: path.to_path_buf(), // convert &Path → owned PathBuf so we can store it
        source,                    // the underlying IO error (e.g. "No such file")
    })?;
    // `?` unwraps Ok(value) or returns Err(WorkflowError) from this function.

    // Step 2: parse the YAML string into our Workflow struct.
    // `serde_yaml::from_str` uses serde's Deserialize impl (generated by the
    // derive macro in model.rs) to convert YAML keys → Rust fields.
    let workflow: Workflow =
        serde_yaml::from_str(&raw).map_err(|source| WorkflowError::ParseYaml {
            path: path.to_path_buf(),
            source, // the serde_yaml parse error (e.g. "missing required field `agents`")
        })?;

    // Step 3: semantic validation — check that agent names, step ids, and
    // gate references are internally consistent (the YAML was syntactically
    // valid but might still be logically broken).
    validate_workflow(&workflow)?;

    Ok(workflow)
}

// =============================================================================
// Learning Notes
// =============================================================================
// • `fs::read_to_string` — reads an entire file into a heap-allocated String.
//   Simple and convenient; fine for config files that are never huge.
// • `map_err(|e| ...)` — transforms the error inside a Result without changing
//   the Ok value.  Common pattern: convert library errors into your own types.
// • `?` operator — if the Result is Err, immediately return that Err from the
//   current function; if it's Ok, unwrap and continue.  Think of it as early-return
//   on failure with automatic type conversion.
// • `path.to_path_buf()` — clones a borrowed `&Path` into an owned `PathBuf`
//   so it can be stored inside the error struct which may outlive this function.
